// Per-die-type geometry, physics, and the orientation data that lets the settle-
// then-relabel trick work for every solid (not just the cube).
//
// The key correctness rule (see the cube-only note in `orient.ts`): the relabel
// applied to the whole die body MUST be an element of the solid's proper rotation
// group, or the body renders resting on an edge. So each shape carries its full
// rotation group; `relabelRotationFor` searches it for the symmetry that brings
// the target face/vertex most world-up. Pure data + math here (three + cannon
// types only) so it's unit-testable without WebGL.

import * as CANNON from "cannon-es";
import * as THREE from "three";
import { RoundedBoxGeometry } from "three/examples/jsm/geometries/RoundedBoxGeometry.js";

import { FACES as CUBE_FACES } from "./orient";

export type DieType = "d4" | "d6" | "d8" | "d10" | "d12" | "d20";

const UP = new THREE.Vector3(0, 1, 0);
const EPS = 1e-6;

/** A value paired with the local direction that points up when that value reads.
 *  For face-read dice `dir` is the outward face normal; for d4 it's a vertex. */
export type ReadAxis = { value: number; dir: THREE.Vector3 };

/** One numbered face for glyph placement: where its centre is, its outward
 *  normal, and an in-plane "up" for orienting the numeral. */
export type FacePlacement = {
  value: number;
  center: THREE.Vector3;
  normal: THREE.Vector3;
  up: THREE.Vector3;
};

export type DieShape = {
  type: DieType;
  readMode: "face" | "vertex";
  /** Circumradius of the mesh/collider (world units). */
  radius: number;
  readAxes: ReadAxis[];
  /** The solid's proper rotation group (unit quaternions incl. identity). */
  rotations: THREE.Quaternion[];
  /** Numbered faces for rendering (empty for d6, which uses pips). */
  placements: FacePlacement[];
  makeGeometry: () => THREE.BufferGeometry;
  makeCollider: () => CANNON.Shape;
};

// ---------- rotation groups ----------

/** Close the set generated by `gens` under composition (BFS by right-multiply,
 *  which reaches every element of a finite group). Dedup by quaternion identity
 *  (|dot| ≈ 1 covers the q ≡ -q double cover). */
function rotationGroup(gens: THREE.Quaternion[]): THREE.Quaternion[] {
  const out = [new THREE.Quaternion()];
  const has = (q: THREE.Quaternion) =>
    out.some((o) => Math.abs(o.dot(q)) > 1 - EPS);
  for (let i = 0; i < out.length && out.length < 200; i++) {
    for (const g of gens) {
      const p = out[i].clone().multiply(g);
      if (!has(p)) out.push(p);
    }
  }
  return out;
}

function quatAbout(axis: THREE.Vector3, angle: number): THREE.Quaternion {
  return new THREE.Quaternion().setFromAxisAngle(
    axis.clone().normalize(),
    angle,
  );
}

// ---------- canonical convex solids ----------

type Poly = {
  verts: THREE.Vector3[];
  /** Each face = ordered vertex indices (auto-oriented outward in `build`). */
  faces: number[][];
};

function v(x: number, y: number, z: number) {
  return new THREE.Vector3(x, y, z);
}

/** Tetrahedron (d4). */
function tetra(): Poly {
  const verts = [v(1, 1, 1), v(-1, -1, 1), v(-1, 1, -1), v(1, -1, -1)];
  const faces = [
    [1, 2, 3],
    [0, 3, 2],
    [0, 1, 3],
    [0, 2, 1],
  ];
  return { verts, faces };
}

/** Octahedron (d8). */
function octa(): Poly {
  const verts = [
    v(1, 0, 0),
    v(-1, 0, 0),
    v(0, 1, 0),
    v(0, -1, 0),
    v(0, 0, 1),
    v(0, 0, -1),
  ];
  const faces = [
    [0, 2, 4],
    [2, 1, 4],
    [1, 3, 4],
    [3, 0, 4],
    [2, 0, 5],
    [1, 2, 5],
    [3, 1, 5],
    [0, 3, 5],
  ];
  return { verts, faces };
}

/** Icosahedron (d20). Golden-ratio coordinates. */
function icosa(): Poly {
  const p = (1 + Math.sqrt(5)) / 2;
  const verts = [
    v(0, 1, p),
    v(0, 1, -p),
    v(0, -1, p),
    v(0, -1, -p),
    v(1, p, 0),
    v(1, -p, 0),
    v(-1, p, 0),
    v(-1, -p, 0),
    v(p, 0, 1),
    v(p, 0, -1),
    v(-p, 0, 1),
    v(-p, 0, -1),
  ];
  // Faces derived by adjacency (edge length 2); auto-oriented in `build`.
  const faces = trianglesFrom(verts, 20);
  return { verts, faces };
}

/** Dodecahedron (d12). 20 verts; 12 pentagon faces built by proximity. */
function dodeca(): Poly {
  const p = (1 + Math.sqrt(5)) / 2;
  const q = 1 / p;
  const verts = [
    v(1, 1, 1),
    v(1, 1, -1),
    v(1, -1, 1),
    v(1, -1, -1),
    v(-1, 1, 1),
    v(-1, 1, -1),
    v(-1, -1, 1),
    v(-1, -1, -1),
    v(0, q, p),
    v(0, q, -p),
    v(0, -q, p),
    v(0, -q, -p),
    v(q, p, 0),
    v(q, -p, 0),
    v(-q, p, 0),
    v(-q, -p, 0),
    v(p, 0, q),
    v(p, 0, -q),
    v(-p, 0, q),
    v(-p, 0, -q),
  ];
  const faces = pentagonsFrom(verts);
  return { verts, faces };
}

/** Pentagonal trapezohedron (d10): two poles + two offset rings of 5 → 10 kites. */
function trapezohedron(): Poly {
  const ring = 1.0;
  const a = 0.35; // ring height (±)
  const h = 1.15; // pole height
  const verts: THREE.Vector3[] = [v(0, h, 0), v(0, -h, 0)];
  for (let k = 0; k < 5; k++) {
    const up = (k * 2 * Math.PI) / 5;
    verts.push(v(ring * Math.cos(up), a, ring * Math.sin(up)));
  }
  for (let k = 0; k < 5; k++) {
    const lo = (k * 2 * Math.PI) / 5 + Math.PI / 5;
    verts.push(v(ring * Math.cos(lo), -a, ring * Math.sin(lo)));
  }
  const U = (k: number) => 2 + (((k % 5) + 5) % 5);
  const L = (k: number) => 7 + (((k % 5) + 5) % 5);
  const faces: number[][] = [];
  for (let k = 0; k < 5; k++) faces.push([0, U(k), L(k), U(k + 1)]); // upper kites
  for (let k = 0; k < 5; k++) faces.push([1, L(k), U(k + 1), L(k + 1)]); // lower kites
  return { verts, faces };
}

/** All 20 triangles of a solid whose faces are equilateral triangles of edge
 *  length `2·|shortest edge|` — used for the icosahedron (proximity search). */
function trianglesFrom(verts: THREE.Vector3[], want: number): number[][] {
  const n = verts.length;
  let min = Infinity;
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++)
      min = Math.min(min, verts[i].distanceTo(verts[j]));
  const adj = (i: number, j: number) =>
    verts[i].distanceTo(verts[j]) < min * 1.05;
  const faces: number[][] = [];
  const seen = new Set<string>();
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++)
      for (let k = j + 1; k < n; k++)
        if (adj(i, j) && adj(j, k) && adj(i, k)) {
          const key = [i, j, k].join(",");
          if (!seen.has(key)) {
            seen.add(key);
            faces.push([i, j, k]);
          }
        }
  return faces.slice(0, want);
}

/** The 12 pentagon faces of the dodecahedron: for each of the 12 "face-centre"
 *  directions, the 5 nearest vertices, ordered around the centre. */
function pentagonsFrom(verts: THREE.Vector3[]): number[][] {
  const p = (1 + Math.sqrt(5)) / 2;
  // Face centres of a dodecahedron point along the icosahedron's vertices.
  const centres = [
    v(0, 1, p),
    v(0, 1, -p),
    v(0, -1, p),
    v(0, -1, -p),
    v(1, p, 0),
    v(1, -p, 0),
    v(-1, p, 0),
    v(-1, -p, 0),
    v(p, 0, 1),
    v(p, 0, -1),
    v(-p, 0, 1),
    v(-p, 0, -1),
  ];
  return centres.map((c) => {
    const cn = c.clone().normalize();
    const near = verts
      .map((vert, i) => ({ i, d: vert.clone().normalize().dot(cn) }))
      .sort((x, y) => y.d - x.d)
      .slice(0, 5)
      .map((x) => x.i);
    // Order the 5 around the centre by angle in the face plane.
    const u = new THREE.Vector3().subVectors(verts[near[0]], c).normalize();
    const w = new THREE.Vector3().crossVectors(cn, u).normalize();
    return near.sort((x, y) => {
      const ax = Math.atan2(
        verts[x].clone().sub(c).dot(w),
        verts[x].clone().sub(c).dot(u),
      );
      const ay = Math.atan2(
        verts[y].clone().sub(c).dot(w),
        verts[y].clone().sub(c).dot(u),
      );
      return ax - ay;
    });
  });
}

// ---------- building a face-read shape from a Poly ----------

function faceCentroid(poly: Poly, face: number[]): THREE.Vector3 {
  const c = new THREE.Vector3();
  for (const i of face) c.add(poly.verts[i]);
  return c.multiplyScalar(1 / face.length);
}

/** Newell normal of a face (robust for near-planar polygons). */
function faceNormal(poly: Poly, face: number[]): THREE.Vector3 {
  const n = new THREE.Vector3();
  for (let i = 0; i < face.length; i++) {
    const a = poly.verts[face[i]];
    const b = poly.verts[face[(i + 1) % face.length]];
    n.x += (a.y - b.y) * (a.z + b.z);
    n.y += (a.z - b.z) * (a.x + b.x);
    n.z += (a.x - b.x) * (a.y + b.y);
  }
  return n.normalize();
}

/** Pair antipodal faces and assign 1..n so opposite faces sum to `sum`. */
function assignOppositeSum(centroids: THREE.Vector3[], sum: number): number[] {
  const n = centroids.length;
  const values = new Array<number>(n).fill(0);
  const dirs = centroids.map((c) => c.clone().normalize());
  let next = 1;
  for (let i = 0; i < n; i++) {
    if (values[i]) continue;
    let anti = -1;
    let best = Infinity;
    for (let j = 0; j < n; j++) {
      if (j === i || values[j]) continue;
      const d = dirs[i].distanceTo(dirs[j].clone().negate());
      if (d < best) {
        best = d;
        anti = j;
      }
    }
    values[i] = next;
    if (anti >= 0) values[anti] = sum - next;
    next++;
  }
  return values;
}

type BuildOpts = {
  type: DieType;
  poly: Poly;
  radius: number;
  oppositeSum: number;
  /** face-order n-fold + vertex-order for the two rotation generators. */
  gens: THREE.Quaternion[];
};

function buildFaceShape(opts: BuildOpts): DieShape {
  const { type, poly, radius } = opts;
  // Scale to the target circumradius.
  const scale = radius / poly.verts[0].length();
  const verts = poly.verts.map((p) => p.clone().multiplyScalar(scale));
  const scaled: Poly = { verts, faces: poly.faces.map((f) => [...f]) };

  // Auto-orient each face CCW as seen from outside (normal points away from 0).
  for (const f of scaled.faces) {
    const nrm = faceNormal(scaled, f);
    if (nrm.dot(faceCentroid(scaled, f)) < 0) f.reverse();
  }

  const centroids = scaled.faces.map((f) => faceCentroid(scaled, f));
  const values = assignOppositeSum(centroids, opts.oppositeSum);
  const normals = scaled.faces.map((f) => faceNormal(scaled, f));

  const readAxes: ReadAxis[] = centroids.map((c, i) => ({
    value: values[i],
    dir: c.clone().normalize(),
  }));

  const placements: FacePlacement[] = scaled.faces.map((f, i) => {
    const normal = normals[i];
    // In-plane "up" for the glyph: project world-up, else the first edge.
    let up = new THREE.Vector3(0, 1, 0).projectOnPlane(normal);
    if (up.lengthSq() < EPS) {
      up = verts[f[0]].clone().sub(centroids[i]).projectOnPlane(normal);
    }
    return {
      value: values[i],
      center: centroids[i],
      normal,
      up: up.normalize(),
    };
  });

  return {
    type,
    readMode: "face",
    radius,
    readAxes,
    rotations: rotationGroup(opts.gens),
    placements,
    makeGeometry: () => polyGeometry(scaled),
    makeCollider: () => polyCollider(scaled),
  };
}

/** Non-indexed flat-shaded mesh: fan-triangulate each face. */
function polyGeometry(poly: Poly): THREE.BufferGeometry {
  const pos: number[] = [];
  for (const f of poly.faces) {
    for (let i = 1; i < f.length - 1; i++) {
      for (const idx of [f[0], f[i], f[i + 1]]) {
        const p = poly.verts[idx];
        pos.push(p.x, p.y, p.z);
      }
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
  g.computeVertexNormals();
  return g;
}

function polyCollider(poly: Poly): CANNON.ConvexPolyhedron {
  const vertices = poly.verts.map((p) => new CANNON.Vec3(p.x, p.y, p.z));
  return new CANNON.ConvexPolyhedron({
    vertices,
    faces: poly.faces.map((f) => [...f]),
  });
}

// ---------- the shape table ----------

const R = 0.5; // base circumradius (a d6 is ~1 unit across; DiceScene scales)

function cubeShape(): DieShape {
  // d6 keeps the pip layout from orient.ts (fixed) + a rounded-box body.
  const readAxes: ReadAxis[] = CUBE_FACES.map((f) => ({
    value: f.value,
    dir: f.normal.clone(),
  }));
  const rot = rotationGroup([
    quatAbout(v(1, 0, 0), Math.PI / 2),
    quatAbout(v(1, 1, 1), (2 * Math.PI) / 3),
  ]);
  const S = R * 1.55; // rounded box edge ~matches the other solids' footprint
  return {
    type: "d6",
    readMode: "face",
    radius: R,
    readAxes,
    rotations: rot,
    placements: [], // pips, drawn by DiceScene
    makeGeometry: () => new RoundedBoxGeometry(S, S, S, 5, S * 0.12),
    makeCollider: () => new CANNON.Box(new CANNON.Vec3(S / 2, S / 2, S / 2)),
  };
}

function faceGens(poly: Poly): THREE.Quaternion[] {
  // n-fold about a face incident to vertex 0 + m-fold about vertex 0. This
  // "flag" generator pair spans the full proper rotation group; the face must
  // touch the vertex so their axes aren't collinear (a tetra's face 0 is
  // opposite vertex 0 → same axis → only C3, not A4).
  const face = poly.faces.find((f) => f.includes(0)) ?? poly.faces[0];
  const vertOrder = poly.faces.filter((f) => f.includes(0)).length;
  return [
    quatAbout(faceCentroid(poly, face), (2 * Math.PI) / face.length),
    quatAbout(poly.verts[0], (2 * Math.PI) / vertOrder),
  ];
}

function d10Shape(): DieShape {
  const poly = trapezohedron();
  const scale = R / poly.verts[0].length();
  // Pole 72° + a horizontal 2-fold through an equatorial edge midpoint → D5.
  const mid = new THREE.Vector3()
    .addVectors(poly.verts[2], poly.verts[7])
    .setY(0)
    .normalize();
  const gens = [
    quatAbout(v(0, 1, 0), (2 * Math.PI) / 5),
    quatAbout(mid, Math.PI),
  ];
  const shape = buildFaceShape({
    type: "d10",
    poly,
    radius: R,
    oppositeSum: 11, // values 1..10 (10 shown as "0"); balanced pairs sum to 11
    gens,
  });
  void scale;
  return shape;
}

function d4Shape(): DieShape {
  const poly = tetra();
  const scale = R / poly.verts[0].length();
  const verts = poly.verts.map((p) => p.clone().multiplyScalar(scale));
  const scaled: Poly = { verts, faces: poly.faces.map((f) => [...f]) };
  for (const f of scaled.faces) {
    if (faceNormal(scaled, f).dot(faceCentroid(scaled, f)) < 0) f.reverse();
  }
  // Vertex-read: each vertex carries a value; the up vertex is read.
  const readAxes: ReadAxis[] = verts.map((p, i) => ({
    value: i + 1,
    dir: p.clone().normalize(),
  }));
  // Numeral at each face corner = that corner-vertex's value (apex convention).
  const placements: FacePlacement[] = [];
  for (const f of scaled.faces) {
    const normal = faceNormal(scaled, f);
    const c = faceCentroid(scaled, f);
    for (const vi of f) {
      const corner = verts[vi];
      const center = corner.clone().lerp(c, 0.42);
      placements.push({
        value: vi + 1,
        center,
        normal,
        up: corner.clone().sub(c).projectOnPlane(normal).normalize(),
      });
    }
  }
  return {
    type: "d4",
    readMode: "vertex",
    radius: R,
    readAxes,
    rotations: rotationGroup(faceGens(poly)),
    placements,
    makeGeometry: () => polyGeometry(scaled),
    makeCollider: () => polyCollider(scaled),
  };
}

let CACHE: Record<DieType, DieShape> | null = null;

export function shapeFor(type: DieType): DieShape {
  if (!CACHE) {
    CACHE = {
      d4: d4Shape(),
      d6: cubeShape(),
      d8: buildFaceShape({
        type: "d8",
        poly: octa(),
        radius: R,
        oppositeSum: 9,
        gens: faceGens(octa()),
      }),
      d10: d10Shape(),
      d12: buildFaceShape({
        type: "d12",
        poly: dodeca(),
        radius: R,
        oppositeSum: 13,
        // The dodecahedron shares the icosahedral rotation group; use the icosa's
        // exact golden-ratio generators (the proximity-built pentagon faces
        // aren't numerically exact enough to close cleanly).
        gens: faceGens(icosa()),
      }),
      d20: buildFaceShape({
        type: "d20",
        poly: icosa(),
        radius: R,
        oppositeSum: 21,
        gens: faceGens(icosa()),
      }),
    };
  }
  return CACHE[type];
}

// ---------- generalized relabel (used by DiceScene) ----------

/** The value whose read-axis points most world-up under `quat`. */
export function shownValueFor(
  quat: THREE.Quaternion,
  readAxes: ReadAxis[],
): number {
  let best = -Infinity;
  let val = readAxes[0].value;
  const t = new THREE.Vector3();
  for (const a of readAxes) {
    const d = t.copy(a.dir).applyQuaternion(quat).dot(UP);
    if (d > best) {
      best = d;
      val = a.value;
    }
  }
  return val;
}

/** The rotation-group element `g` such that, applied to the body already at
 *  `rest` (final = rest·g), the `target` value's read-axis is most world-up —
 *  i.e. `shownValueFor(rest·g) === target`. Because `g` is a symmetry, the body
 *  still renders resting correctly. */
export function relabelRotationFor(
  target: number,
  rest: THREE.Quaternion,
  shape: DieShape,
): THREE.Quaternion {
  const axis = (
    shape.readAxes.find((a) => a.value === target) ?? shape.readAxes[0]
  ).dir;
  let best = -Infinity;
  let pick = shape.rotations[0];
  const t = new THREE.Vector3();
  for (const g of shape.rotations) {
    const d = t.copy(axis).applyQuaternion(g).applyQuaternion(rest).dot(UP);
    if (d > best) {
      best = d;
      pick = g;
    }
  }
  return pick.clone();
}

// ---------- d100 ----------

/** Expand a d100 roll value (1..100) into its two display dice: a tens d10
 *  (shown 00..90) and a units d10 (shown 0..9). 100 → "00" + "0". */
export function d100Digits(value: number): { tens: number; units: number } {
  const m = value % 100; // 100 → 0
  return { tens: Math.floor(m / 10), units: m % 10 };
}
