// Per-die-type geometry, physics, and the orientation data that lets the settle-
// then-relabel trick work for every solid (not just the cube).
//
// The key correctness rule (see the cube-only note in `orient.ts`): the relabel
// applied to the whole die body MUST be an element of the solid's proper rotation
// group, or the body renders resting on an edge. So each shape carries its full
// rotation group; `relabelRotationFor` searches it for the symmetry that brings
// the target face/vertex most world-up. Pure data + math here (three + cannon
// types only) so it's unit-testable without WebGL.

import * as CANNON from "cannon-es";
import * as THREE from "three";
import { RoundedBoxGeometry } from "three/examples/jsm/geometries/RoundedBoxGeometry.js";

import { FACES as CUBE_FACES } from "./orient";

export type DieType = "d4" | "d6" | "d8" | "d10" | "d12" | "d20";

const UP = new THREE.Vector3(0, 1, 0);
const EPS = 1e-6;

/** A value paired with the local direction that points up when that value reads.
 *  For face-read dice `dir` is the outward face normal; for d4 it's a vertex. */
export type ReadAxis = { value: number; dir: THREE.Vector3 };

/** One numbered face for glyph placement: where its centre is, its outward
 *  normal, and an in-plane "up" for orienting the numeral. */
export type FacePlacement = {
  value: number;
  center: THREE.Vector3;
  normal: THREE.Vector3;
  up: THREE.Vector3;
};

export type DieShape = {
  type: DieType;
  readMode: "face" | "vertex";
  /** Circumradius of the mesh/collider (world units). */
  radius: number;
  /** Center→nearest-face distance = the height it rests at (face down). */
  inradius: number;
  readAxes: ReadAxis[];
  /** Outward unit normal of every face — the directions that can point straight
   *  down at a stable rest (used by the settle "flatten" pass). */
  restNormals: THREE.Vector3[];
  /** The solid's proper rotation group (unit quaternions incl. identity). */
  rotations: THREE.Quaternion[];
  /** Numbered faces for rendering (empty for d6, which uses pips). */
  placements: FacePlacement[];
  /** `rounded` → smooth-shaded body (soft edges); else flat facets. */
  makeGeometry: (rounded: boolean) => THREE.BufferGeometry;
  makeCollider: () => CANNON.Shape;
};

// ---------- rotation groups ----------

/** Close the set generated by `gens` under composition (BFS by right-multiply,
 *  which reaches every element of a finite group). Dedup by quaternion identity
 *  (|dot| ≈ 1 covers the q ≡ -q double cover). */
function rotationGroup(gens: THREE.Quaternion[]): THREE.Quaternion[] {
  const out = [new THREE.Quaternion()];
  const has = (q: THREE.Quaternion) =>
    out.some((o) => Math.abs(o.dot(q)) > 1 - EPS);
  for (let i = 0; i < out.length && out.length < 200; i++) {
    for (const g of gens) {
      const p = out[i].clone().multiply(g);
      if (!has(p)) out.push(p);
    }
  }
  return out;
}

function quatAbout(axis: THREE.Vector3, angle: number): THREE.Quaternion {
  return new THREE.Quaternion().setFromAxisAngle(
    axis.clone().normalize(),
    angle,
  );
}

// ---------- canonical convex solids ----------

type Poly = {
  verts: THREE.Vector3[];
  /** Each face = ordered vertex indices (auto-oriented outward in `build`). */
  faces: number[][];
};

function v(x: number, y: number, z: number) {
  return new THREE.Vector3(x, y, z);
}

/** Tetrahedron (d4). */
function tetra(): Poly {
  const verts = [v(1, 1, 1), v(-1, -1, 1), v(-1, 1, -1), v(1, -1, -1)];
  const faces = [
    [1, 2, 3],
    [0, 3, 2],
    [0, 1, 3],
    [0, 2, 1],
  ];
  return { verts, faces };
}

/** Octahedron (d8). */
function octa(): Poly {
  const verts = [
    v(1, 0, 0),
    v(-1, 0, 0),
    v(0, 1, 0),
    v(0, -1, 0),
    v(0, 0, 1),
    v(0, 0, -1),
  ];
  const faces = [
    [0, 2, 4],
    [2, 1, 4],
    [1, 3, 4],
    [3, 0, 4],
    [2, 0, 5],
    [1, 2, 5],
    [3, 1, 5],
    [0, 3, 5],
  ];
  return { verts, faces };
}

/** Icosahedron (d20). Golden-ratio coordinates. */
function icosa(): Poly {
  const p = (1 + Math.sqrt(5)) / 2;
  const verts = [
    v(0, 1, p),
    v(0, 1, -p),
    v(0, -1, p),
    v(0, -1, -p),
    v(1, p, 0),
    v(1, -p, 0),
    v(-1, p, 0),
    v(-1, -p, 0),
    v(p, 0, 1),
    v(p, 0, -1),
    v(-p, 0, 1),
    v(-p, 0, -1),
  ];
  // Faces derived by adjacency (edge length 2); auto-oriented in `build`.
  const faces = trianglesFrom(verts, 20);
  return { verts, faces };
}

/** Dodecahedron (d12). 20 verts; 12 pentagon faces built by proximity. */
function dodeca(): Poly {
  const p = (1 + Math.sqrt(5)) / 2;
  const q = 1 / p;
  const verts = [
    v(1, 1, 1),
    v(1, 1, -1),
    v(1, -1, 1),
    v(1, -1, -1),
    v(-1, 1, 1),
    v(-1, 1, -1),
    v(-1, -1, 1),
    v(-1, -1, -1),
    v(0, q, p),
    v(0, q, -p),
    v(0, -q, p),
    v(0, -q, -p),
    v(q, p, 0),
    v(q, -p, 0),
    v(-q, p, 0),
    v(-q, -p, 0),
    v(p, 0, q),
    v(p, 0, -q),
    v(-p, 0, q),
    v(-p, 0, -q),
  ];
  const faces = pentagonsFrom(verts);
  return { verts, faces };
}

/** Pentagonal trapezohedron (d10): two poles + two offset rings of 5 → 10 kite
 *  faces. The pole height is SOLVED so each kite is planar — otherwise its two
 *  render triangles crease and the die reads as a 20-facet blob, not a d10. */
function trapezohedron(): Poly {
  const ring = 1.0;
  const a = 0.16; // equatorial ring half-height (tunes the d10 aspect)
  const step = (2 * Math.PI) / 5;
  const U0 = v(ring, a, 0);
  const U1 = v(ring * Math.cos(step), a, ring * Math.sin(step));
  const L0 = v(ring * Math.cos(step / 2), -a, ring * Math.sin(step / 2));
  // Plane normal of the k=0 upper kite's ring vertices; the pole T=(0,h,0) lies
  // on that plane when h = (U0·N)/N.y → all kites planar (by symmetry).
  const n = new THREE.Vector3()
    .subVectors(U1, U0)
    .cross(new THREE.Vector3().subVectors(L0, U0));
  const h = U0.dot(n) / n.y;
  const verts: THREE.Vector3[] = [v(0, h, 0), v(0, -h, 0)];
  for (let k = 0; k < 5; k++)
    verts.push(v(ring * Math.cos(k * step), a, ring * Math.sin(k * step)));
  for (let k = 0; k < 5; k++)
    verts.push(
      v(
        ring * Math.cos(k * step + step / 2),
        -a,
        ring * Math.sin(k * step + step / 2),
      ),
    );
  const U = (k: number) => 2 + (((k % 5) + 5) % 5);
  const L = (k: number) => 7 + (((k % 5) + 5) % 5);
  const faces: number[][] = [];
  for (let k = 0; k < 5; k++) faces.push([0, U(k), L(k), U(k + 1)]); // upper kites
  for (let k = 0; k < 5; k++) faces.push([1, L(k), U(k + 1), L(k + 1)]); // lower kites
  return { verts, faces };
}

/** All 20 triangles of a solid whose faces are equilateral triangles of edge
 *  length `2·|shortest edge|` — used for the icosahedron (proximity search). */
function trianglesFrom(verts: THREE.Vector3[], want: number): number[][] {
  const n = verts.length;
  let min = Infinity;
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++)
      min = Math.min(min, verts[i].distanceTo(verts[j]));
  const adj = (i: number, j: number) =>
    verts[i].distanceTo(verts[j]) < min * 1.05;
  const faces: number[][] = [];
  const seen = new Set<string>();
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++)
      for (let k = j + 1; k < n; k++)
        if (adj(i, j) && adj(j, k) && adj(i, k)) {
          const key = [i, j, k].join(",");
          if (!seen.has(key)) {
            seen.add(key);
            faces.push([i, j, k]);
          }
        }
  return faces.slice(0, want);
}

/** The 12 pentagon faces of the dodecahedron: for each of the 12 "face-centre"
 *  directions, the 5 nearest vertices, ordered around the centre. */
function pentagonsFrom(verts: THREE.Vector3[]): number[][] {
  const p = (1 + Math.sqrt(5)) / 2;
  // Face centres of THIS dodecahedron point along cyclic perms of (0, φ, 1) — the
  // dual icosahedron's vertices. (Not (0, 1, φ): with these verts the φ/1 slots
  // are swapped, and getting it wrong groups non-coplanar verts into junk faces.)
  const centres = [
    v(0, p, 1),
    v(0, p, -1),
    v(0, -p, 1),
    v(0, -p, -1),
    v(1, 0, p),
    v(-1, 0, p),
    v(1, 0, -p),
    v(-1, 0, -p),
    v(p, 1, 0),
    v(p, -1, 0),
    v(-p, 1, 0),
    v(-p, -1, 0),
  ];
  return centres.map((dir) => {
    const cn = dir.clone().normalize();
    const near = verts
      .map((vert, i) => ({ i, d: vert.clone().normalize().dot(cn) }))
      .sort((x, y) => y.d - x.d)
      .slice(0, 5)
      .map((x) => x.i);
    // Order the 5 around the TRUE face centroid (not the centre direction, whose
    // magnitude differs) so the pentagon isn't wound into a self-crossing bowtie.
    const c = new THREE.Vector3();
    for (const i of near) c.add(verts[i]);
    c.multiplyScalar(1 / near.length);
    const nrm = c.clone().normalize();
    const u = new THREE.Vector3().subVectors(verts[near[0]], c).normalize();
    const w = new THREE.Vector3().crossVectors(nrm, u).normalize();
    return near.sort((x, y) => {
      const ax = Math.atan2(
        verts[x].clone().sub(c).dot(w),
        verts[x].clone().sub(c).dot(u),
      );
      const ay = Math.atan2(
        verts[y].clone().sub(c).dot(w),
        verts[y].clone().sub(c).dot(u),
      );
      return ax - ay;
    });
  });
}

// ---------- building a face-read shape from a Poly ----------

function faceCentroid(poly: Poly, face: number[]): THREE.Vector3 {
  const c = new THREE.Vector3();
  for (const i of face) c.add(poly.verts[i]);
  return c.multiplyScalar(1 / face.length);
}

/** Normal of a face's first fan triangle — the SAME winding `polyGeometry` and
 *  the collider use, so orienting by it guarantees the rendered/colliding faces
 *  point outward (the Newell normal can disagree in sign for a fan). */
function fanNormal(poly: Poly, face: number[]): THREE.Vector3 {
  const a = poly.verts[face[0]];
  const b = poly.verts[face[1]];
  const c = poly.verts[face[2]];
  return new THREE.Vector3()
    .subVectors(b, a)
    .cross(new THREE.Vector3().subVectors(c, a))
    .normalize();
}

/** Pair antipodal faces and assign 1..n so opposite faces sum to `sum`. */
function assignOppositeSum(centroids: THREE.Vector3[], sum: number): number[] {
  const n = centroids.length;
  const values = new Array<number>(n).fill(0);
  const dirs = centroids.map((c) => c.clone().normalize());
  let next = 1;
  for (let i = 0; i < n; i++) {
    if (values[i]) continue;
    let anti = -1;
    let best = Infinity;
    for (let j = 0; j < n; j++) {
      if (j === i || values[j]) continue;
      const d = dirs[i].distanceTo(dirs[j].clone().negate());
      if (d < best) {
        best = d;
        anti = j;
      }
    }
    values[i] = next;
    if (anti >= 0) values[anti] = sum - next;
    next++;
  }
  return values;
}

type BuildOpts = {
  type: DieType;
  poly: Poly;
  radius: number;
  oppositeSum: number;
  /** face-order n-fold + vertex-order for the two rotation generators. */
  gens: THREE.Quaternion[];
};

function buildFaceShape(opts: BuildOpts): DieShape {
  const { type, poly, radius } = opts;
  // Scale to the target circumradius.
  const scale = radius / poly.verts[0].length();
  const verts = poly.verts.map((p) => p.clone().multiplyScalar(scale));
  const scaled: Poly = { verts, faces: poly.faces.map((f) => [...f]) };

  // Auto-orient each face so its fan winds CCW as seen from outside.
  for (const f of scaled.faces) {
    if (fanNormal(scaled, f).dot(faceCentroid(scaled, f)) < 0) f.reverse();
  }

  const centroids = scaled.faces.map((f) => faceCentroid(scaled, f));
  const values = assignOppositeSum(centroids, opts.oppositeSum);
  // Outward normal = the centroid direction (unambiguously outward for a convex
  // solid centred at the origin), used for numeral placement.
  const normals = centroids.map((c) => c.clone().normalize());

  const readAxes: ReadAxis[] = centroids.map((c, i) => ({
    value: values[i],
    dir: c.clone().normalize(),
  }));

  const placements: FacePlacement[] = scaled.faces.map((f, i) => {
    const normal = normals[i];
    // In-plane "up" for the glyph: project world-up, else the first edge.
    let up = new THREE.Vector3(0, 1, 0).projectOnPlane(normal);
    if (up.lengthSq() < EPS) {
      up = verts[f[0]].clone().sub(centroids[i]).projectOnPlane(normal);
    }
    return {
      value: values[i],
      center: centroids[i],
      normal,
      up: up.normalize(),
    };
  });

  return {
    type,
    readMode: "face",
    radius,
    inradius: Math.min(...centroids.map((c) => c.length())),
    readAxes,
    restNormals: normals.map((n) => n.clone()),
    rotations: rotationGroup(opts.gens),
    placements,
    makeGeometry: (rounded) => polyGeometry(scaled, rounded),
    makeCollider: () => polyCollider(scaled),
  };
}

/** Build a flat-shaded mesh from a list of triangles, winding each one outward
 *  (a convex solid centred at the origin → the outward normal agrees with the
 *  triangle centroid direction), so callers needn't track winding. */
function trianglesToGeometry(tris: THREE.Vector3[][]): THREE.BufferGeometry {
  const pos: number[] = [];
  const n = new THREE.Vector3();
  const cen = new THREE.Vector3();
  for (const [a, b, c] of tris) {
    n.subVectors(b, a).cross(cen.subVectors(c, a));
    cen.copy(a).add(b).add(c);
    const ordered = n.dot(cen) < 0 ? [a, c, b] : [a, b, c]; // flip inward-facing tris
    for (const p of ordered) pos.push(p.x, p.y, p.z);
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
  g.computeVertexNormals(); // non-indexed → flat per-face shading
  return g;
}

/** Flat-faceted mesh: fan-triangulate each face. */
function flatGeometry(poly: Poly): THREE.BufferGeometry {
  const tris: THREE.Vector3[][] = [];
  for (const f of poly.faces)
    for (let i = 1; i < f.length - 1; i++)
      tris.push([poly.verts[f[0]], poly.verts[f[i]], poly.verts[f[i + 1]]]);
  return trianglesToGeometry(tris);
}

// ---------- true rounded body ----------
//
// The same construction RoundedBoxGeometry uses for the d6, generalized to any
// convex isohedral solid: shrink the solid so every face plane moves inward by
// the bevel radius `r`, then offset the whole surface back out by `r` — the
// Minkowski sum of the inner solid with a sphere. Faces stay flat (and at the
// original plane distance, so resting height and numerals are unchanged), each
// edge becomes a true cylinder section, each vertex a true sphere patch. Every
// vertex carries its exact analytic normal, so the bevel shades perfectly
// smooth at low tessellation — no facet approximation, no winding guesswork.

const ROUND_SEG = 5; // arc segments per bevel (matches the d6's RoundedBox)
// Bevel radius as a fraction of the inradius. 0.24 reproduces the d6 exactly:
// its RoundedBox radius is edge·0.12 = (edge/2)·0.24 = inradius·0.24.
const ROUND_K = 0.24;

/** Unit directions along the great-circle arc from `n1` to `n2` (inclusive). */
function arcDirs(
  n1: THREE.Vector3,
  n2: THREE.Vector3,
  seg: number,
): THREE.Vector3[] {
  const ang = Math.acos(THREE.MathUtils.clamp(n1.dot(n2), -1, 1));
  const sn = Math.sin(ang);
  const out: THREE.Vector3[] = [];
  for (let j = 0; j <= seg; j++) {
    const t = j / seg;
    out.push(
      ang < EPS
        ? n1.clone()
        : n1
            .clone()
            .multiplyScalar(Math.sin((1 - t) * ang) / sn)
            .addScaledVector(n2, Math.sin(t * ang) / sn),
    );
  }
  return out;
}

/** Each edge (a,b) with the indices of its two adjacent faces. */
function edgeList(
  poly: Poly,
): { a: number; b: number; f1: number; f2: number }[] {
  const m = new Map<string, { a: number; b: number; f1: number; f2: number }>();
  poly.faces.forEach((f, fi) => {
    for (let i = 0; i < f.length; i++) {
      const a = f[i];
      const b = f[(i + 1) % f.length];
      const key = a < b ? `${a}_${b}` : `${b}_${a}`;
      const e = m.get(key);
      if (e) e.f2 = fi;
      else m.set(key, { a, b, f1: fi, f2: -1 });
    }
  });
  return [...m.values()].filter((e) => e.f2 >= 0);
}

/** The faces incident to vertex `vi`, in rotational order around it — walk
 *  face→face across the shared edge (vi, next-vertex-after-vi). Exact adjacency,
 *  no angle sorting to get subtly wrong. */
function faceCycleAt(poly: Poly, vi: number): number[] {
  const inc = poly.faces
    .map((_, fi) => fi)
    .filter((fi) => poly.faces[fi].includes(vi));
  const cycle = [inc[0]];
  while (cycle.length < inc.length) {
    const cur = cycle[cycle.length - 1];
    const f = poly.faces[cur];
    const w = f[(f.indexOf(vi) + 1) % f.length];
    const next = inc.find(
      (fi) => fi !== cur && poly.faces[fi].includes(w) && !cycle.includes(fi),
    );
    if (next === undefined) break;
    cycle.push(next);
  }
  return cycle;
}

function roundedGeometry(raw: Poly): THREE.BufferGeometry {
  // Orient every face CCW-from-outside first: the vertex-cap walk below needs a
  // consistent half-edge structure (each directed edge in exactly one face).
  const poly: Poly = {
    verts: raw.verts,
    faces: raw.faces.map((f) =>
      fanNormal(raw, f).dot(faceCentroid(raw, f)) < 0 ? [...f].reverse() : f,
    ),
  };
  // Exact outward unit face-plane normals (faces are planar — tested).
  const N = poly.faces.map((f) => fanNormal(poly, f));
  // Face-plane distance — identical for every face of an isohedral die.
  const d = Math.min(...poly.faces.map((f, i) => N[i].dot(poly.verts[f[0]])));
  const r = ROUND_K * d;
  const s = (d - r) / d; // uniform shrink = every face plane in by exactly r
  const inner = poly.verts.map((p) => p.clone().multiplyScalar(s));

  const pos: number[] = [];
  const nrm: number[] = [];
  // Emit one triangle with per-vertex normals, wound outward (for a convex
  // solid centred at the origin, outward ⇔ geometric normal · centroid > 0).
  const tri = (
    pa: THREE.Vector3,
    pb: THREE.Vector3,
    pc: THREE.Vector3,
    na: THREE.Vector3,
    nb: THREE.Vector3,
    nc: THREE.Vector3,
  ) => {
    const g = new THREE.Vector3()
      .subVectors(pb, pa)
      .cross(new THREE.Vector3().subVectors(pc, pa));
    const cen = new THREE.Vector3().copy(pa).add(pb).add(pc);
    const P = g.dot(cen) >= 0 ? [pa, pb, pc] : [pa, pc, pb];
    const Nn = g.dot(cen) >= 0 ? [na, nb, nc] : [na, nc, nb];
    for (const p of P) pos.push(p.x, p.y, p.z);
    for (const n of Nn) nrm.push(n.x, n.y, n.z);
  };
  const at = (vi: number, u: THREE.Vector3) =>
    inner[vi].clone().addScaledVector(u, r);

  // 1) Flat faces: the inner face pushed back out by r (lands on the original
  //    face plane, shrunk toward its centre — numerals stay on it).
  poly.faces.forEach((f, fi) => {
    const p = f.map((vi) => at(vi, N[fi]));
    for (let i = 1; i < p.length - 1; i++)
      tri(p[0], p[i], p[i + 1], N[fi], N[fi], N[fi]);
  });

  // 2) Edge bands: a cylinder section along the inner edge, sweeping the normal
  //    from one face plane to the other. Normals = the swept direction → the
  //    band shades as a true cylinder.
  for (const { a, b, f1, f2 } of edgeList(poly)) {
    const arc = arcDirs(N[f1], N[f2], ROUND_SEG);
    for (let j = 0; j < ROUND_SEG; j++) {
      const u0 = arc[j];
      const u1 = arc[j + 1];
      tri(at(a, u0), at(b, u0), at(b, u1), u0, u0, u1);
      tri(at(a, u0), at(b, u1), at(a, u1), u0, u1, u1);
    }
  }

  // 3) Vertex caps: a sphere patch fanned from the corner's mean direction to
  //    the ring of edge-arc directions. The ring reuses the exact arc samples
  //    the edge bands end on, so the surface is watertight.
  for (let vi = 0; vi < poly.verts.length; vi++) {
    const cycle = faceCycleAt(poly, vi);
    const ring: THREE.Vector3[] = [];
    for (let i = 0; i < cycle.length; i++) {
      const arc = arcDirs(
        N[cycle[i]],
        N[cycle[(i + 1) % cycle.length]],
        ROUND_SEG,
      );
      for (let j = 0; j < ROUND_SEG; j++) ring.push(arc[j]); // last = next's first
    }
    const c = ring
      .reduce((sum, u) => sum.add(u), new THREE.Vector3())
      .normalize();
    for (let k = 0; k < ring.length; k++) {
      const u0 = ring[k];
      const u1 = ring[(k + 1) % ring.length];
      tri(at(vi, c), at(vi, u0), at(vi, u1), c, u0, u1);
    }
  }

  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute("normal", new THREE.Float32BufferAttribute(nrm, 3));
  return g;
}

function polyGeometry(poly: Poly, rounded: boolean): THREE.BufferGeometry {
  return rounded ? roundedGeometry(poly) : flatGeometry(poly);
}

function polyCollider(poly: Poly): CANNON.ConvexPolyhedron {
  const vertices = poly.verts.map((p) => new CANNON.Vec3(p.x, p.y, p.z));
  return new CANNON.ConvexPolyhedron({
    vertices,
    faces: poly.faces.map((f) => [...f]),
  });
}

// ---------- the shape table ----------

const D6_EDGE = 1.1; // d6 cube edge — matches DiceScene's DIE so d6 is unchanged
// Polyhedra circumradius ≈ the d6's (edge·√3/2 ≈ 0.95) so a mixed tray reads as
// one matched set rather than the cube dwarfing the rest.
const R = D6_EDGE * 0.82;

function cubeShape(): DieShape {
  // d6 keeps the pip layout from orient.ts (fixed) + a rounded-box body.
  const readAxes: ReadAxis[] = CUBE_FACES.map((f) => ({
    value: f.value,
    dir: f.normal.clone(),
  }));
  const rot = rotationGroup([
    quatAbout(v(1, 0, 0), Math.PI / 2),
    quatAbout(v(1, 1, 1), (2 * Math.PI) / 3),
  ]);
  const S = D6_EDGE;
  return {
    type: "d6",
    readMode: "face",
    radius: R,
    inradius: S / 2,
    readAxes,
    restNormals: CUBE_FACES.map((f) => f.normal.clone()),
    rotations: rot,
    placements: [], // pips, drawn by DiceScene
    makeGeometry: (rounded) =>
      rounded
        ? new RoundedBoxGeometry(S, S, S, 5, S * 0.12)
        : new THREE.BoxGeometry(S, S, S),
    makeCollider: () => new CANNON.Box(new CANNON.Vec3(S / 2, S / 2, S / 2)),
  };
}

function faceGens(poly: Poly): THREE.Quaternion[] {
  // n-fold about a face incident to vertex 0 + m-fold about vertex 0. This
  // "flag" generator pair spans the full proper rotation group; the face must
  // touch the vertex so their axes aren't collinear (a tetra's face 0 is
  // opposite vertex 0 → same axis → only C3, not A4).
  const face = poly.faces.find((f) => f.includes(0)) ?? poly.faces[0];
  const vertOrder = poly.faces.filter((f) => f.includes(0)).length;
  return [
    quatAbout(faceCentroid(poly, face), (2 * Math.PI) / face.length),
    quatAbout(poly.verts[0], (2 * Math.PI) / vertOrder),
  ];
}

function d10Shape(): DieShape {
  const poly = trapezohedron();
  // Pole 72° + a horizontal 2-fold through an equatorial edge midpoint → D5.
  const mid = new THREE.Vector3()
    .addVectors(poly.verts[2], poly.verts[7])
    .setY(0)
    .normalize();
  const gens = [
    quatAbout(v(0, 1, 0), (2 * Math.PI) / 5),
    quatAbout(mid, Math.PI),
  ];
  return buildFaceShape({
    type: "d10",
    poly,
    radius: R,
    oppositeSum: 11, // values 1..10 (10 shown as "0"); balanced pairs sum to 11
    gens,
  });
}

function d4Shape(): DieShape {
  const poly = tetra();
  const scale = R / poly.verts[0].length();
  const verts = poly.verts.map((p) => p.clone().multiplyScalar(scale));
  const scaled: Poly = { verts, faces: poly.faces.map((f) => [...f]) };
  for (const f of scaled.faces) {
    if (fanNormal(scaled, f).dot(faceCentroid(scaled, f)) < 0) f.reverse();
  }
  // Vertex-read: each vertex carries a value; the up vertex is read.
  const readAxes: ReadAxis[] = verts.map((p, i) => ({
    value: i + 1,
    dir: p.clone().normalize(),
  }));
  // Numeral at each face corner = that corner-vertex's value (apex convention).
  const placements: FacePlacement[] = [];
  for (const f of scaled.faces) {
    const normal = fanNormal(scaled, f);
    const c = faceCentroid(scaled, f);
    for (const vi of f) {
      const corner = verts[vi];
      const center = corner.clone().lerp(c, 0.42);
      placements.push({
        value: vi + 1,
        center,
        normal,
        up: corner.clone().sub(c).projectOnPlane(normal).normalize(),
      });
    }
  }
  return {
    type: "d4",
    readMode: "vertex",
    radius: R,
    inradius: Math.min(
      ...scaled.faces.map((f) => faceCentroid(scaled, f).length()),
    ),
    readAxes,
    restNormals: scaled.faces.map((f) => fanNormal(scaled, f)),
    rotations: rotationGroup(faceGens(poly)),
    placements,
    makeGeometry: (rounded) => polyGeometry(scaled, rounded),
    makeCollider: () => polyCollider(scaled),
  };
}

let CACHE: Record<DieType, DieShape> | null = null;

export function shapeFor(type: DieType): DieShape {
  if (!CACHE) {
    CACHE = {
      d4: d4Shape(),
      d6: cubeShape(),
      d8: buildFaceShape({
        type: "d8",
        poly: octa(),
        radius: R,
        oppositeSum: 9,
        gens: faceGens(octa()),
      }),
      d10: d10Shape(),
      d12: buildFaceShape({
        type: "d12",
        poly: dodeca(),
        radius: R,
        oppositeSum: 13,
        // The dodecahedron shares the icosahedral rotation group; use the icosa's
        // exact golden-ratio generators (the proximity-built pentagon faces
        // aren't numerically exact enough to close cleanly).
        gens: faceGens(icosa()),
      }),
      d20: buildFaceShape({
        type: "d20",
        poly: icosa(),
        radius: R,
        oppositeSum: 21,
        gens: faceGens(icosa()),
      }),
    };
  }
  return CACHE[type];
}

// ---------- generalized relabel (used by DiceScene) ----------

/** The value whose read-axis points most world-up under `quat`. */
export function shownValueFor(
  quat: THREE.Quaternion,
  readAxes: ReadAxis[],
): number {
  let best = -Infinity;
  let val = readAxes[0].value;
  const t = new THREE.Vector3();
  for (const a of readAxes) {
    const d = t.copy(a.dir).applyQuaternion(quat).dot(UP);
    if (d > best) {
      best = d;
      val = a.value;
    }
  }
  return val;
}

/** The rotation-group element `g` such that, applied to the body already at
 *  `rest` (final = rest·g), the `target` value's read-axis is most world-up —
 *  i.e. `shownValueFor(rest·g) === target`. Because `g` is a symmetry, the body
 *  still renders resting correctly. */
export function relabelRotationFor(
  target: number,
  rest: THREE.Quaternion,
  shape: DieShape,
): THREE.Quaternion {
  const axis = (
    shape.readAxes.find((a) => a.value === target) ?? shape.readAxes[0]
  ).dir;
  let best = -Infinity;
  let pick = shape.rotations[0];
  const t = new THREE.Vector3();
  for (const g of shape.rotations) {
    const d = t.copy(axis).applyQuaternion(g).applyQuaternion(rest).dot(UP);
    if (d > best) {
      best = d;
      pick = g;
    }
  }
  return pick.clone();
}

// ---------- d100 ----------

/** Expand a d100 roll value (1..100) into its two display dice: a tens d10
 *  (shown 00..90) and a units d10 (shown 0..9). 100 → "00" + "0". */
export function d100Digits(value: number): { tens: number; units: number } {
  const m = value % 100; // 100 → 0
  return { tens: Math.floor(m / 10), units: m % 10 };
}
